### PR TITLE
more demos annoucements + assets

### PR DESCRIPTION
**Pull request by vicshi06**
more demos for testing purpose

### CODE REVIEW

**Comment by ben9583** [comment]
Just a quick question; why JFIF image?

**Comment by vicshi06** [comment]
I actually don't know. This is the format it gave me when I downloaded the image. I tried to choose JPEG but it didn't work for this image.

And I think we should host the images on `static.ocf.berkeley.edu` so we can just grab the image instead of downloading it.

**Comment by ben9583** [comment]
> I actually don't know. This is the format it gave me when I downloaded the image. I tried to choose JPEG but it didn't work for this image.

Let's maybe just replace it with a standard image format; there may be markdown rendering issues for certain browsers.

> And I think we should host the images on static.ocf.berkeley.edu so we can just grab the image instead of downloading it.

We actually don't need to make an API request to load the images. If you simply link to the image in GitHub, then append `?raw=true`, you get the image itself. For instance, [this image](https://github.com/ocf/ocfstatic/blob/master/static/assets/img/cloud.jpg) can be put into a raw form by copying the link and appending: `https://github.com/ocf/ocfstatic/blob/master/static/assets/img/cloud.jpg?raw=true`

Example:
image

For this reason, I don't think we actually need to host the image on `ocfstatic`, especially since that'll mean someone will have to make two pull requests for such an announcement.

**Comment by vicshi06** [comment]
cool! looks great to me. thanks for the commit by the way

**Review by ben9583 — APPROVED** [review]

**Pull request merged**
