### PR TITLE
Create Announcements Repo

### LINKED ISSUE #48: Create Announcements Repo
We'll be creating a GitHub repository for our announcements, which should contain markdown files for announcements. The idea is that OCF staff can create announcements by uploading a markdown file, which our backend tools will be able to retrieve to display using our API.

- [x] Create the repository (link here when done)
- [x] Define schema for repository (how it is structured)
- [x] Define schema for markdown files

### PR DESCRIPTION
**Pull request by vicshi06**
https://github.com/ocf/api/issues/48

### CODE REVIEW

**Comment by ben9583** [comment]
Following from discussion on [the linked issue](https://github.com/ocf/api/issues/48), lgtm. We'll def need to redo the README with more details on creating an announcement and stuff, but we can wait until more of the technical details, like CI/CD, are implemented.

**Review by ben9583 — APPROVED** [review]

**Review by ben9583 — APPROVED** [review]

**Comment by ben9583** [comment]
Hmm for some reason it's not letting me merge even with approval

**Comment by vicshi06** [comment]
Let me push a demo announcement so I can test out the `ocflib` functions.

Also, can you check if the settings for this repo are correct? Not sure what the standard should be for OCF.

**Comment by ben9583** [comment]
I don't seem to have permissions to view the settings for this repo (probably why my review isn't authoritative)

**Review by ben9583 — APPROVED** [review]

**Comment by vicshi06** [comment]
it should work now. Can you take a look at the settings just to make sure i didn't forget any important security features?

**Pull request merged**
